///////////////////////////////////////////////////////////
//  HockeyTeam.cs
//  Implementation of the Class HockeyTeam
//  Generated by Enterprise Architect
//  Created on:      01-dec-2020 17:04:48
//  Original author: uzivatel
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class HockeyTeam : Team {

	public HockeyTeam(){

	}

	~HockeyTeam(){

	}

}//end HockeyTeam