///////////////////////////////////////////////////////////
//  HockeyReportDescription.cs
//  Implementation of the Class HockeyReportDescription
//  Generated by Enterprise Architect
//  Created on:      01-dec-2020 17:04:44
//  Original author: uzivatel
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class HockeyReportDescription : ReportDescription {

	public HockeyReportDescription(){

	}

	~HockeyReportDescription(){

	}

}//end HockeyReportDescription