///////////////////////////////////////////////////////////
//  HtmlReportBuilder.cs
//  Implementation of the Class HtmlReportBuilder
//  Generated by Enterprise Architect
//  Created on:      01-dec-2020 17:04:52
//  Original author: uzivatel
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class HtmlReportBuilder : ReportBuilder {

	public HtmlReportBuilder(){

	}

	~HtmlReportBuilder(){

	}

	/// 
	/// <param name="p"></param>
	public String AddHeader(String p){

		return "";
	}

	/// 
	/// <param name="p"></param>
	public String AddInfo(String p){

		return "";
	}

	/// 
	/// <param name="p"></param>
	public String AddTeams(String p){

		return "";
	}

	/// 
	/// <param name="p"></param>
	public String AddMatches(String p){

		return "";
	}

	/// 
	/// <param name="p"></param>
	public Report GetReport(String p){

		return null;
	}

}//end HtmlReportBuilder