///////////////////////////////////////////////////////////
//  PdfReportBuilder.cs
//  Implementation of the Class PdfReportBuilder
//  Generated by Enterprise Architect
//  Created on:      01-dec-2020 17:05:03
//  Original author: uzivatel
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class PdfReportBuilder : ReportBuilder {

	public PdfReportBuilder(){

	}

	~PdfReportBuilder(){

	}

	/// 
	/// <param name="p"></param>
	public String AddHeader(String p){

		return "";
	}

	/// 
	/// <param name="p"></param>
	public String AddInfo(String p){

		return "";
	}

	/// 
	/// <param name="p"></param>
	public String AddTeams(String p){

		return "";
	}

	/// 
	/// <param name="p"></param>
	public String AddMatches(String p){

		return "";
	}

	/// 
	/// <param name="p"></param>
	public Report GetReport(String p){

		return null;
	}

}//end PdfReportBuilder