///////////////////////////////////////////////////////////
//  ReportDescription.cs
//  Implementation of the Class ReportDescription
//  Generated by Enterprise Architect
//  Created on:      01-dec-2020 17:05:13
//  Original author: uzivatel
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class ReportDescription {

	public ReportDescription(){

	}

	~ReportDescription(){

	}

}//end ReportDescription