///////////////////////////////////////////////////////////
//  ReportGenerator.cs
//  Implementation of the Class ReportGenerator
//  Generated by Enterprise Architect
//  Created on:      01-dec-2020 17:05:17
//  Original author: uzivatel
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class ReportGenerator {

	public ReportBuilder m_ReportBuilder;

	public ReportGenerator(){

	}

	~ReportGenerator(){

	}

	/// 
	/// <param name="r"></param>
	public void GenerateReport(ReportDescription r){

	}

}//end ReportGenerator