///////////////////////////////////////////////////////////
//  ReportBuilder.cs
//  Implementation of the Interface ReportBuilder
//  Generated by Enterprise Architect
//  Created on:      01-dec-2020 17:05:10
//  Original author: uzivatel
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public interface ReportBuilder  {

	/// 
	/// <param name="p"></param>
	String AddHeader(String p);

	/// 
	/// <param name="p"></param>
	String AddInfo(String p);

	/// 
	/// <param name="p"></param>
	String AddTeams(String p);

	/// 
	/// <param name="p"></param>
	String AddMatches(String p);

	/// 
	/// <param name="p"></param>
	Report GetReport(String p);
}//end ReportBuilder