///////////////////////////////////////////////////////////
//  Report.cs
//  Implementation of the Class Report
//  Generated by Enterprise Architect
//  Created on:      01-dec-2020 17:05:07
//  Original author: uzivatel
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Report {

	public Report(){

	}

	~Report(){

	}

}//end Report