///////////////////////////////////////////////////////////
//  Team.cs
//  Implementation of the Class Team
//  Generated by Enterprise Architect
//  Created on:      01-dec-2020 17:05:30
//  Original author: uzivatel
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Team {

	public Team(){

	}

	~Team(){

	}

}//end Team